services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.17.3'
    container_name: elasticSearch
    environment:
      - 'ELASTIC_PASSWORD=AnSTXrcuYAL5kSc8Wsjq'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - '9200:9200'
    depends_on:
      - mysql
  mysql:
    image: 'mysql:latest'
    container_name: mysql-container
    environment:
      - 'MYSQL_DATABASE=abertoAgoraDatabase'
      - 'MYSQL_ROOT_PASSWORD=root'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: {}