services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.17.3'
    container_name: elasticsearch
    environment:
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - '9200:9200'
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 20s
      timeout: 10s
      retries: 10

  mysql:
    image: 'mysql:latest'
    container_name: mysql-container
    environment:
      - 'MYSQL_DATABASE=abertoAgoraDatabase'
      - 'MYSQL_ROOT_PASSWORD=root'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 20s
      timeout: 5s
      retries: 10

  spring-boot:
    build:
      context: .
    image: abertoagora
    container_name: spring-app
    environment:
      - 'spring.datasource.url=jdbc:mysql://mysql:3306/abertoAgoraDatabase?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC'
      - 'spring.datasource.username=root'
      - 'spring.datasource.password=root'
      - 'spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver'
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
      - 'elasticsearch.enabled=true'
      - 'SPRING_PORT=8081'
    ports:
      - '8081:8080'
    depends_on:
      elasticsearch:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - app-network
    command: /wait-for-it.sh mysql:3306 -- /wait-for-it.sh elasticsearch:9200 -- java -jar /app.jar
networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: {}
